apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-backend
  description: Team responsabile dei microservizi backend del PetStore
spec:
  type: team
  profile:
    displayName: Team Backend
  children: []
  members:
    - dario.rizzo
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dario.rizzo
  description: Developer del team backend
spec:
  profile:
    displayName: Dario Rizzo
    email: dario.rizzo@tuaazienda.com
  memberOf:
    - team-backend
