apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-backend
  description: Team responsabile dei microservizi backend del PetStore
spec:
  type: team
  profile:
    displayName: Team Backend
  children: []
  members:
    - dariorizzorai
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dariorizzorai
  description: Developer del team backend
spec:
  profile:
    displayName: Dario Rizzo
    email: dario.rizzo.1@rai.it
  memberOf:
    - team-backend
